name: era_pro
description: "A new Flutter project."
flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/constants
  filename: assets.dart
publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: any
  intl: any
  encrypt: ^5.0.3
  equatable: ^2.0.5
  crypto_dart: any
  dartz: ^0.10.1
  http: any
  json_annotation: ^4.9.0
  shared_preferences:
  drift: ^2.19.1+1
  sqlite3: ^2.1.0
  path_provider:
  font_awesome_flutter:
  sqlite3_flutter_libs: any
  device_info_plus: any
  # qrscan: any
  animated_custom_dropdown: any
  flutter_slidable: any

  currency_textfield: ^4.14.1
  currency_text_input_formatter: ^2.2.6
  dropdown_search: ^6.0.1

  fl_chart: ^0.69.2
  image_picker: ^1.1.2
  lottie: ^2.7.0
  flutter_colorpicker: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: any
  json_serializable: any

  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
