name: era_pro
description: "A new Flutter project."
flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/constants
  filename: assets.dart
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: any
  intl: any
  encrypt: ^5.0.3
  equatable: ^2.0.5
  crypto_dart: any
  dartz: ^0.10.1
  http: any
  json_annotation: ^4.9.0
  shared_preferences:
  drift: ^2.19.1+1
  sqlite3: ^2.1.0
  path_provider:
  font_awesome_flutter:
  sqlite3_flutter_libs: any
  device_info_plus: any
  # qrscan: any
  animated_custom_dropdown: any
  flutter_slidable: any

  currency_textfield: ^4.14.1
  currency_text_input_formatter: ^2.2.6
  dropdown_search: ^6.0.1

  fl_chart: ^0.69.2
  image_picker: ^1.1.2
  lottie: ^2.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  build_runner: any
  json_serializable: any

  drift_dev: ^2.14.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: ntaqat
      fonts:
        - asset: assets/fonts/ntaqat.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
